runtime: nodejs20
env: flex
entrypoint: npm run start

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: "glass-next:us-central1:vendure-db"

env_variables:
  # Application
  APP_ENV: "production"
  PORT: "8080"
  NODE_ENV: "production"

  # Database Configuration (Cloud SQL)
  DB_TYPE: "postgres"
  DB_HOST: "/cloudsql/glass-next:us-central1:vendure-db"
  DB_PORT: "5432"
  DB_NAME: "vendure"
  DB_USERNAME: "vendure"
  DB_PASSWORD: "YAXNqZB2DBu8NENFJTIBA"
  DB_SCHEMA: "public"

  # Authentication
  SUPERADMIN_USERNAME: "superadmin"
  SUPERADMIN_PASSWORD: "superadmin"
  COOKIE_SECRET: "your-cookie-secret-here-change-this-in-production"

  # SMTP Configuration (for email)
  SMTP_HOST: "smtp.gmail.com"
  SMTP_USER: "your-email@gmail.com"
  SMTP_PASSWORD: "your-app-password"

  # Elasticsearch Configuration (you'll need to set up Elasticsearch separately)
  ELASTICSEARCH_HOST: "https://your-elasticsearch-instance.com"
  ELASTICSEARCH_PORT: "443"

  # Redis Configuration (Cloud Memorystore)
  REDIS_HOST: "10.x.x.x"  # Replace with your Redis instance IP
  REDIS_PORT: "6379"

  # Stripe Configuration
  STRIPE_SECRET_KEY: "sk_live_your_stripe_secret_key"
  STRIPE_PUBLISHABLE_KEY: "pk_live_your_stripe_publishable_key"
  STRIPE_WEBHOOK_SECRET: "whsec_your_webhook_secret"

  # Google Cloud Project
  GCLOUD_PROJECT: "glass-next"