steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/g-next-backend/vendure-backend:latest', '.', '-f', 'Dockerfile']
    id: 'Build'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/g-next-backend/vendure-backend:latest']
    id: 'Push'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'vendure-backend'
      - '--platform=managed'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/g-next-backend/vendure-backend:latest'
      - '--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID'
      - '--region=us-central1'
      - '--port=8080'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--timeout=900'
      - '--set-env-vars=NODE_ENV=production,APP_ENV=production,DB_TYPE=postgres,DB_HOST=34.171.38.108,DB_PORT=5432,DB_NAME=vendure,DB_USERNAME=vendure,DB_PASSWORD=yAXHq2BZB0Hu8NENFJTIBA,DB_SCHEMA=public,SUPERADMIN_USERNAME=superadmin,SUPERADMIN_PASSWORD=superadmin,COOKIE_SECRET=your-cookie-secret-here-change-this-in-development,INIT_DB=true,ELASTICSEARCH_HOST=http://34.27.160.130,ELASTICSEARCH_PORT=9200,REDIS_HOST=localhost,REDIS_PORT=6379,ADMIN_UI_API_HOST=https://vendure-backend-393513168568.us-central1.run.app,FRONTEND_URL=https://gcommerce.glass'
      - '--quiet'
    id: 'Deploy'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/g-next-backend/vendure-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

substitutions:
  _TRIGGER_ID: '82afd9b2-1ac5-49d7-b407-4ad8bf5d51e8'

tags:
  - 'gcp-cloud-build-deploy-cloud-run'
  - 'gcp-cloud-build-deploy-cloud-run-managed'
  - 'vendure-backend'