version: '3.8'

services:
  vendure-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - APP_ENV=production
      - PORT=8080
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=vendure
      - DB_USERNAME=vendure
      - DB_PASSWORD=YAXNqZB2DBu8NENFJTIBA
      - DB_SCHEMA=public
      - SUPERADMIN_USERNAME=superadmin
      - SUPERADMIN_PASSWORD=superadmin
      - COOKIE_SECRET=your-cookie-secret-here-change-this-in-production
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vendure
      - POSTGRES_USER=vendure
      - POSTGRES_PASSWORD=YAXNqZB2DBu8NENFJTIBA
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
