name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: glass-next
  SERVICE_NAME: vendure-backend
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test --if-present

    - name: Build application
      run: npm run build

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port 8080 \
          --memory 2Gi \
          --cpu 1 \
          --max-instances 10 \
          --min-instances 0 \
          --timeout 900 \
          --set-env-vars NODE_ENV=production,APP_ENV=production,PORT=443,DB_TYPE=postgres,DB_HOST=34.171.38.108,DB_PORT=5432,DB_NAME=vendure,DB_USERNAME=vendure,DB_PASSWORD=YAXNqZB2DBu8NENFJTIBA,DB_SCHEMA=public,SUPERADMIN_USERNAME=superadmin,SUPERADMIN_PASSWORD=superadmin,COOKIE_SECRET=your-cookie-secret-here-change-this-in-development,INIT_DB=true,ELASTICSEARCH_HOST=http://34.27.160.130,ELASTICSEARCH_PORT=9200,REDIS_HOST=localhost,REDIS_PORT=6379,ADMIN_UI_API_HOST=https://vendure-backend-393513168568.us-central1.run.app

    - name: Run database migrations
      run: |
        gcloud run jobs create migrate-db \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --region $REGION \
          --set-env-vars NODE_ENV=production,APP_ENV=production \
          --command "npx" \
          --args "vendure,migrate,--run" \
          --max-retries 3
